spring.application.name=petworld-platform
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=petshop;encrypt=true;trustServerCertificate=true;useUnicode=true;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=200105
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Kích ho?t multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.resolve-lazily=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.servlet.session.tracking-modes=cookie
#LOGIN WITH GOOGLE
spring.security.oauth2.client.registration.google.client-id=514283828109-j3qm14ujbpmssdvicpp7665caukt44c8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
#VERIFY EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=petworldfpt@gmail.com
spring.mail.password=jfdg rpvp xxkt kyuf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
